spring:
  profiles:
    active:
      - "qa"
  jpa:
    show-sql: true
  application:
    name: orders
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
build:
  version: "1.0"
info:
  message: "Welcome to busycoder order default profile"
  name: "Raj: Product Owner order default profile"